In [7]:
no=int(input("Enter no"))
count=0

if(no>1):
    for i in range(1,no+1):
        if(no%i)==0:
            count=count+1
    if(count==2):
        print("Number is prime")
    else:
        print("Number is Not Prime")
else:
    print("Enter valid no")

Enter no2
Number is prime


In [9]:
no=int(input("Enter no"))
count=0

if(no>1):
    for i in range(1,no+1):
        if no%i==0:
            count+=1
    if (count==2):
        print("Prime")
    else:
        print("Not prime")
else:
       print("Enter Valid NO")
       

Enter no9
Not prime


In [20]:
a=2
b=3
print("a:",a,"b:",b)

temp=a
a=b
b=temp

print("a:",a,"b:",b)

a: 2 b: 3
a: 3 b: 2


In [10]:
a=56
b=97

temp=a
a=b
b=temp
print(a,b)

97 56


In [21]:
a=2
b=3
print("a:",a,"b:",b)

a=a+b
b=a-b
a=a-b

print("a:",a,"b:",b)

a: 2 b: 3
a: 3 b: 2


In [11]:
a=56
b=97

a=a+b
b=a-b
a=a-b

print(a,b)

97 56


In [25]:
a="abcdef"
print(a[::-1])

fedcba


In [36]:
a="abcdef"
s=""
l=len(a)
for i in a[l-1::-1]:
    s += i
print(s)

fedcba


In [44]:

a=input("Enter String")

def check_palindrom(x):
    l=len(x)
    x=x.lower()
    i=0
    j=l-1
    
    while i<j:
        if(x[i]!=x[j]):
            return False
        i+=1
        j-=1
    return True
print(check_palindrom(a))

Enter Stringnitin
True


In [2]:

st=input("Enter String")

def check_palin(x):
    l=len(x)
    x=x.lower()
    i=0
    j=l-1
    
    while i<j:
        if x[i]!=x[j]:
            return False
        i+=1
        j-=1
    return True
print(check_palin(st))

Enter Stringdfgfgg
False


In [2]:
#sort the list
ls=[5,8,1,10,4,6,7]

for i in range(len(ls)):
    for j in range(i+1,len(ls)):
        if ls[j]<ls[i]:
            ls[i],ls[j]=ls[j],ls[i]
print(ls)
    

[1, 4, 5, 6, 7, 8, 10]


In [ ]:
lst = [2,5,7,5,3,4,5,2]
a=[]
min=lst[0]
while lst:
    for i in lst:
        if i<min:
            min=i
            a.append(min)
    
a

In [1]:
arr=[5,4,3,6,9]
max=arr[0]

for i in arr:
    if i>max:
        max=i
print(max)

9


In [3]:
arr=[5,4,3,6,9]
new=sorted(arr)
new

[3, 4, 5, 6, 9]

In [4]:
arr=[5,4,3,6,9]
new=sorted(arr,reverse=True)
new

[9, 6, 5, 4, 3]

In [1]:
ls = [2,5,7,5,3,4,5,2]

def duplicate(ls):
    empty=[]
    ass=[]
    for i in ls:
        if i not in empty:
            empty.append(i)
    print(empty)
    for i in range(len(empty)):
        for j in range(i+1,len(empty)):
            if empty[j]<empty[i]:
                  empty[i],empty[j]=empty[j],empty[i]
    print(empty)
duplicate( [2,5,7,5,3,4,5,2])

[2, 5, 7, 3, 4]
[2, 3, 4, 5, 7]


In [15]:
# Find the second largest no

list1 = [10, 20, 20, 4, 45, 45, 45, 99, 99]
empty=[]

for i in list1:
    if i not in empty:
        empty.append(i)
for i in range(len(empty)):
    for j in range(i+1,len(empty)):
        if empty[j]>empty[i]:
            empty[i],empty[j]=empty[j],empty[i]
print(empty)
print(empty[1])

[99, 45, 20, 10, 4]
45


In [23]:
list1 = [10, 20, 20, 4, 45, 45, 45, 99, 99]
list1=list(set(list1))
list1=sorted(list1)
print("Second Highest number is",list1[-2])

Second Highest number is 45


In [2]:
# 0 1 1 2 3 5 8 13 21 34
def fibonacci(n):
    if n<0:
        print("Invalid Input")
    elif n==0:
        return 0
    elif n==1 or n==2:
        return 1
    else:
        return fibonacci(n-1)+fibonacci(n-2)
    
print(fibonacci(5))

5


In [26]:
# reverse the string


mylist = [5,8,9,6,3]
mylist=mylist[::-1]
mylist

[3, 6, 9, 8, 5]

In [29]:
mylist = [5,8,9,6,3]
s=[]
for i in mylist[len(mylist)-1::-1]:
    s.append(i)
s

[3, 6, 9, 8, 5]

In [31]:
# Checking string is palindrome or not
mystring = 'malam'

new=mystring[::-1]

if(mystring==new):
    print("Its palindrome")
else:
    print("Its Not palindrome")



Its palindrome


In [36]:
# Find the duplicate numbers

mylist = [1,1,1,1,2,3,3,6,9,7,6]
new=[]
for i in mylist:
    if mylist.count(i)>1:
        new.append(i)
print(list(set(new)))

[1, 3, 6]


In [43]:
mylist = [1,1,1,1,2,3,3,6,9,7,6]

new=list(set([x for x in mylist if mylist.count(x)>1]))
new

[1, 3, 6]

In [47]:
# find the numbers of words in a given string

mystring = 'Maintaining & expending the database of prospects for the organization.'
print((len(mystring.split())))

10


In [51]:
# extract didgit from given string

mystring = 'Maintaining 12345 & expending 12345 the database of prospects for 12345 the org'
digit=''

for i in mystring:
    if i.isdigit()==True:
        digit+=i
digit


'123451234512345'

In [16]:
# extract didgit from given string

mystring = 'Maintaining 12345 & expending 12345 the database of prospects for 12345 the org'
mystring.split(' ')
new=[]
for i in mystring:
    if i.isdigit():
        new.append(i)
print(new)

['1', '2', '3', '4', '5', '1', '2', '3', '4', '5', '1', '2', '3', '4', '5']


In [17]:
# mystring = 'Maintaining 12345 & expending 12345 the database of prospects for 12345 the org'
mystring.rstrip().split()

['Maintaining',
 '12345',
 '&',
 'expending',
 '12345',
 'the',
 'database',
 'of',
 'prospects',
 'for',
 '12345',
 'the',
 'org']

In [4]:
# factorial of number

def facto(n):
    if n<0:
        return "Number Invalid"
    elif n==1:
        return 1
    elif n==0:
        return 1
    else:
        return n * facto(n-1)
# find the factorial series

print(facto(0))

1


In [66]:
# factorial of number

def facto(n):
    fact=1
    if n<0:
        return "Number Invalid"
    elif n==1:
        return 1
    elif n==0:
        return 0
    else:
        for i in range(2,n+1):
            fact=fact*i
        return fact
        
# find the factorial series

print(facto(5))

120


In [78]:
no=153
sum=0
s=str(no)
l=len(str(no))
for i in s:
    sum+=int(i)**l
if sum==no:
    print("Its Armstrong no")
else:
    print("Its not Armstrong no ")

Its Armstrong no


In [86]:
# Right angle Triangle
num=int(input("Enter number"))

for i in range(1,num+1):
    for j in range(i):
        print('*',end=' ')
    print()

Enter number5
* 
* * 
* * * 
* * * * 
* * * * * 


In [92]:
num=int(input("Enter no"))

for i in range(0,num+1):
    for j in range(i):
        print('*', end=" ")
    print()

Enter no5

* 
* * 
* * * 
* * * * 
* * * * * 


In [94]:
num=int(input("Enter no"))

for i in range(1,num+1):
    for j in range(i):
        print(j+1,end=' ')
    print()

Enter no5
1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [97]:
num=int(input("Enter no"))

for i in range(1,num+1):
    for j in range((num-i)+1):
        print('*',end=" ")
    print()

Enter no5
* * * * * 
* * * * 
* * * 
* * 
* 


In [98]:
num=int(input("Enter no"))

for i in range(1,num+1):
    for j in range((num-i)+1):
        print(j+1,end=" ")
    print()

Enter no5
1 2 3 4 5 
1 2 3 4 
1 2 3 
1 2 
1 


In [103]:
# pyramid of stars
k=0
num=int(input("Enter no"))

for i in range(1,num+1):
    for space in range(1,(num-i)+1):
        print(end=" ")
    while k != (2*i)-1:
        print('*',end="")
        k+=1
    k=0
    print()

Enter no5
    *
   ***
  *****
 *******
*********


In [111]:
#Leap year

year=int(input("Enter year:"))

if year%4==0:
    print("It's Leap Year")
elif year%100==0 and year%400==0:
    print("It's Leap Year")
else:
    print("It's Not Leap Year")




Enter year:2052
It's Leap Year


In [113]:
num = int(input('Enter a number : '))
flag = 0
for i in range(2,num):
     if num%i == 0:
        flag = flag + 1

if flag==0:
     print('Its prime number')
else:
     print('Not Prime')

Enter a number : 2
Its prime number


In [120]:
# Count of maximum occouring letter and number of times it is repeated
mystring = 'Hello everyone, good afternoon'
dic={}

for i in mystring:
    if i in dic:
        dic[i]=dic[i]+1
    else:
        dic[i]=1
print(dic)

{'H': 1, 'e': 5, 'l': 2, 'o': 6, ' ': 3, 'v': 1, 'r': 2, 'y': 1, 'n': 3, ',': 1, 'g': 1, 'd': 1, 'a': 1, 'f': 1, 't': 1}


In [124]:
# Display Count of any perticular element in a string
string = 'aaaasssssssssddddddddf'
search='a'
l={}

for i in  string:
    if i in l:
        l[i]=l[i]+1
    else:
        l[i]=1
print(l)
print(l[search])       




{'a': 4, 's': 9, 'd': 8, 'f': 1}
4


In [1]:
#prime
count=0
no=int(input("Enter number"))
if(no<1):
    print("Enter valid no")
else:
    for i in range(1,no+1):
        if(no%i==0):
            count+=1
    if(count==2):
        print("Its Prime")
    else:
        print("Its Not prime")

Enter number2
Its Prime


In [6]:
no=int(input("Enter no"))
fact=0
if(no<1):
    print("Enter valid no")
else:
    for i in range(2,no):
        if no%i==0:
            fact=fact+1
    if(fact==0):
        print("Its Prime")
    else:
        print("Its Not prime")

Enter no11
Its Prime


In [20]:
#reverse string

a="abcd"
print(a[::-1])

dcba


In [18]:
a="abcd"
s=""
for i in a[len(a)-1::-1]:
    s+=i
print(s)

dcba


In [4]:
#palindrom
a="Nitin"
l=a.lower()
left=0
right=len(l)-1
while left<right:
    if l[left]!=l[right]:
        print("Not Palindrom")
    
    left=left+1
    right=right-1
print("Its Palindrom")
    

Its Palindrom


In [2]:

a=input("Enter String")

def check_palindrom(x):
    l=len(x)
    x=x.lower()
    i=0
    j=l-1
    
    while i<j:
        if(x[i]!=x[j]):
            return False
        i+=1
        j-=1
    return True
print(check_palindrom(a))

Enter StringNitin
True


In [3]:
no1=int(input("Enter number"))
no=str(no1)
l=len(no)
sum=0
for i in no:
     sum+=int(i)**l
if sum==no1:
    print("Its Armstrong")
else:
    print("Not Armstrong")
    

Enter number123
Not Armstrong


In [36]:
num=int(input("Enter number"))

for i in range(1,num+1):
    for j in range(i):
        print(j+1,end=' ')
    print()


Enter number5
1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [35]:
num=int(input("Enter number"))

for i in range(1,num+1):
    for j in range(i):
        print('*',end=' ')
    print()


Enter number5
* 
* * 
* * * 
* * * * 
* * * * * 


In [34]:
num=int(input("Enter number"))

for i in range(1,num+1):
    for j in range(1,num+1):
        print('*',end=' ')
    print()

Enter number5
* * * * * 
* * * * * 
* * * * * 
* * * * * 
* * * * * 


In [33]:
num=int(input("Enter number"))

for row in range(1,num+1):
    for col in range(1,num+1):
        if col==1 or row==5 or row==col:
            print('*',end=' ')
        else:
            print(end='  ')
    print()

Enter number5
*         
* *       
*   *     
*     *   
* * * * * 


In [42]:
num=int(input("Enter number"))

for row in range(1,num+1):
    for col in range(1,num+1):
        if row==4 or (row==1 and col==4)or(row==2 and col==3)or(row==2 and col==5)or(row==3 and col==2)or(row==3 and col==6):
            print('*',end=' ')
        else:
            print(end='  ')
    print()

Enter number7
      *       
    *   *     
  *       *   
* * * * * * * 
              
              
              


In [43]:
num=int(input("Enter no"))
fact=1
for i in range(1,num+1):
    fact=fact*i
print(fact)

Enter no4
24


In [50]:
import math
result=math.factorial(4)
result

24

In [52]:
num=int(input("Enter no"))
def facto(no):
    if no==0:
        return 1
    else:
        return no*facto(no-1)

print(facto(num))

Enter no4
24


In [59]:
lower=int(input("Enter starting no"))
upper=int(input("Enter last no"))

for num in range(lower,upper+1):
    if num>1:
        for i in range(2,num):
            if num%i==0:
                break
        else:
                print(num)

Enter starting no1
Enter last no50
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47


In [10]:
#perfect number
num=int(input("Enter no"))
sum=0
for i in range(1,num):
    if num%i==0:
        sum+=i
if sum==num:
     print("Its perfect number")
    
else:
    print("Not perfect number")

Enter no29
Not perfect number


In [75]:
l=[1,2,4,4]
for i in l:
    for j in l[1::1]:
        sum=i+j
        
if sum==8:
    print("pair is:",i,j)
else:
    print("No such pair whose sum is 8")

pair is: 4 4


In [76]:
#swap no 

a=2
b=3
a,b=b,a
a,b

(3, 2)

In [78]:
#swap no 

a=2
b=3

temp=a
a=b
b=temp
a,b

(3, 2)

In [79]:
#swap no 

a=2
b=3

a=a+b
b=a-b
a=a-b

a,b

(3, 2)

In [3]:
no=int(input("Enter number"))

def prime(num):
    count=0
    if no>1:
        for i in range(1,num+1):
            if num%i==0:
                count+=1
        if count==2:
            print("Its Prime")
        else:
            print("Not prime")
print(prime(no))

Enter number4
Not prime
None


In [7]:
no=int(input("Enter number"))

def prime(num):
    flag=True
    for i in range(2,num):
        if num%2==0:
            flag=False
    return flag
print(prime(no))

Enter number4
False


In [12]:
no=int(input("Enter number"))

def facto(num):
    fact=1
    for i in range(1,num+1):
        fact=fact*i
    return fact
print(facto(no))

Enter number0
1


In [15]:
no=int(input("Enter number"))

def facto(num):
    if num==0:
        return 1
    else:
        return num*facto(num-1)
print(facto(no))

Enter number6
720


In [17]:
#fibonacci

no=int(input("Enter number"))
def fibo(num):
    if num==1:
        return 0
    elif num==2 or num==3:
        return 1
    else:
        return fibo(num-1)+fibo(num-2)
print(fibo(no))


Enter number7
8


In [21]:
a=0
b=1
for i in range(8):
    sum=a+b
    print(sum,end=" ")
    a=b
    b=sum
    


1 2 3 5 8 13 21 34 

In [22]:
# sum of the elements
sum=0
l=[1,2,3,4,5]
for i in l:
    sum+=i
print(sum)

15


In [29]:
# find max & min element

arr=[1,2,3,4,5]
min=arr[0]
max=arr[0]

for i in arr:
    if i<min:
        min=i
for i in arr:
    if i>max:
        max=i 
print("min:",min)
print("max:",max)

min: 1
max: 5


In [35]:
l=[12,35,9,56,24]
n1=[]
n2=[]
n1.append(l[0])
l.remove(l[0])
n2.append(l[-1])
l.remove(l[-1])
n2.extend(l)
n2.extend(n1)
n2

[24, 35, 9, 56, 12]

In [36]:
l=[12,35,9,56,24]
size=len(l)
a=l[0]
l[0]=l[size-1]
l[size-1]=a

l


[24, 35, 9, 56, 12]

In [51]:
# find the min difference betn 2 ele

l1=[5,32,45,4,12,18,25]
def min_dif(arr):
    arr=sorted(arr)
    size=len(arr)
    min_diff=99*99
    
    for i in range(size-1):
        if arr[i+1]-arr[i]< min_diff:
            min_diff= arr[i+1]-arr[i]
        print(arr)
        return min_diff
    
print(min_dif(l1))


[4, 5, 12, 18, 25, 32, 45]
1


In [52]:
# find the common letter beetweeen two string

s1="NAINA"
s2="REENE"
s3=""
s4=""

for i in s1:
    if i not in s3:
        s3+=i
for i in s2:
    if i not in s4:
        s4+=i
for i in s3:
    if i in s4:
        print(i)

N


In [53]:

def find_comm():
    str1=input("Enter 1st string")
    str2=input("Enter 2nd string")
    s1=set(str1)
    s2=set(str2)
    for i in s1:
        if i in s2:
            print(i)
print(find_comm())

Enter 1st stringREENA
Enter 2nd stringNAINA
A
N
None


In [56]:
# Convert two lists into dictionary

list1=['Naina','kimi','Sheena']
list2=[856,256,256]
dic={}
dic=dict(zip(list1,list2))
dic

{'Naina': 856, 'kimi': 256, 'Sheena': 256}

In [4]:
l1=[1,2,3,4,5]
l2=['Nagpur','pune','mumbai','delhi','chennai']
d1=dict(zip(l1,l2))
print(d1)


{1: 'Nagpur', 2: 'pune', 3: 'mumbai', 4: 'delhi', 5: 'chennai'}


In [25]:
d1={}
d1[1]="Ram"
d1[2]="sita"
d1[3]="janak"

print(d1)

for i in d1.keys():
    print(i)
    
for i in d1.values():
    print(i)



{1: 'Ram', 2: 'sita', 3: 'janak'}
1
2
3
Ram
sita
janak
Ram


In [26]:
print(d1[1])

Ram


In [27]:
print(d1[2])

sita


In [28]:
print(d1[3])

janak


In [30]:
# update dict

d1[4]="ravan"

In [31]:
d1

{1: 'Ram', 2: 'sita', 3: 'janak', 4: 'ravan'}

In [32]:
#remove key 4
del d1[4]
d1

{1: 'Ram', 2: 'sita', 3: 'janak'}

In [33]:
print(d1.keys())

dict_keys([1, 2, 3])


In [34]:
print(d1.items())

dict_items([(1, 'Ram'), (2, 'sita'), (3, 'janak')])


In [35]:
for key in d1:
    print(key,d1[key])

1 Ram
2 sita
3 janak


In [37]:
for key, value in d1.items():
    print(key,value)

1 Ram
2 sita
3 janak


In [38]:
for i in d1:
    print(i,d1[i])

1 Ram
2 sita
3 janak


In [40]:
dic={}
dic[1]='A'
dic[2]='B'
dic[3]='C'
dic[4]='D'

dic

{1: 'A', 2: 'B', 3: 'C', 4: 'D'}

In [41]:
l1=[5,6,7,8]
l2=['E','F','G','H']

print(dict(zip(l1,l2)))

{5: 'E', 6: 'F', 7: 'G', 8: 'H'}


In [42]:
del dic[4]
dic

{1: 'A', 2: 'B', 3: 'C'}

In [43]:
# display only key

print(dic.keys())

dict_keys([1, 2, 3])


In [44]:
for key in dic:
    print(key)

1
2
3


In [45]:
#display only values
print(dic.values())

dict_values(['A', 'B', 'C'])


In [49]:
for value in dic:
    print(dic[value])

A
B
C


In [50]:
#print both key and values

print(dic)

{1: 'A', 2: 'B', 3: 'C'}


In [51]:
print(dic.items())

dict_items([(1, 'A'), (2, 'B'), (3, 'C')])


In [52]:
for key in dic:
    print(key,dic[key])

1 A
2 B
3 C


In [54]:
for key, value in dic.items():
    print(key,value)

1 A
2 B
3 C


In [58]:

my_dict=dict(zip(l1,l2))
my_dict

{5: 'E', 6: 'F', 7: 'G', 8: 'H'}

In [60]:
for key in my_dict:
    print(key)

5
6
7
8


In [61]:
print(my_dict.keys())

dict_keys([5, 6, 7, 8])


In [62]:
for value in my_dict:
    print(my_dict[value])

E
F
G
H


In [63]:
print(my_dict.values())

dict_values(['E', 'F', 'G', 'H'])


In [64]:
for key in my_dict:
    print(key,my_dict[key])

5 E
6 F
7 G
8 H


In [65]:
for key,value in my_dict.items():
    print(key,value)

5 E
6 F
7 G
8 H


In [66]:
my_dict.clear()
my_dict

{}

In [68]:
del my_dict
my_dict

NameError: name 'my_dict' is not defined

In [74]:
# verified the given key is exist into dictionary or not

dict1={"suresh":526,"ramesh":623,"pankaj":564,"raj":456}
user_in=input("Enter the key")

if user_in in dict1:
    print("key is exist")
    print("value of key",user_in," is:",dict1[user_in])
else:
    print("Key is not exist")

Enter the keysuresh
key is exist
value of key  suresh  is: 526


In [78]:
# concatenate two dictionary

dict1={"suresh":526,"ramesh":623,"pankaj":564,"raj":456}
dict2={"shyam":523,"ram":601}

dict1.update(dict2)
dict1

{'suresh': 526,
 'ramesh': 623,
 'pankaj': 564,
 'raj': 456,
 'shyam': 523,
 'ram': 601}

In [79]:
# multiply the all the values of dictionary

dict3={"a":3,"b":4,"c":6,"d":5}
mul=1

for i in dict3.values():   # by default we iterate key
    mul*=i
mul


360

In [80]:

dict3={"a":3,"b":4,"c":6,"d":5}
mul=1

for value in dict3:
    mul*=dict3[value]
mul

360

In [81]:
# sum the all the values of dictionary

dict3={"a":3,"b":4,"c":6,"d":5}
sum=0

for value in dict3.values():
    sum+=value
sum



18

In [88]:
d={}
l1=[1,2,3,4,5]
l2=['Nagpur','pune','mumbai','delhi','chennai']

for key,value in zip(l1,l2):
    d[key]=value
d

#############   OR   ###########

print(dict(zip(l1,l2)))

{1: 'Nagpur', 2: 'pune', 3: 'mumbai', 4: 'delhi', 5: 'chennai'}

In [106]:
# count the frequency of character of given string

string=input("Enter string")
string=string.lower()
l=string.split()
d1={}

for i in l:
    if i not in d1.keys():
        d1[i]=0
    d1[i]=d1[i]+1
d1

Enter stringhi how hi hello how


{'hi': 2, 'how': 2, 'hello': 1}

In [109]:
st=int(input("Enter 1st no"))
ls=int(input("Enter last no"))

d2={}
for i in range(st,ls+1):
    d2[i]=i**2
d2
    
    

Enter 1st no1
Enter last no10


{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}

In [110]:
st=int(input("Enter 1st no"))
ls=int(input("Enter last no"))

d3={i:i**2 for i in range(st,ls+1)}
d3

Enter 1st no1
Enter last no10


{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}

In [112]:
l1=[1,2,3,4,5]
l2=['Nagpur','pune','mumbai','delhi','chennai']
d={}

def dic(l1,l2):
    for i in range(len(l1)):
        d[l1[i]]=l2[i]
    return d
print(dic(l1,l2))

{1: 'Nagpur', 2: 'pune', 3: 'mumbai', 4: 'delhi', 5: 'chennai'}


In [113]:
l1=[1,2,3,4,5]
l2=['Nagpur','pune','mumbai','delhi','chennai']
d1={}
def dictionary(key,value):
    for i in range(len(key)):
        d1[key[i]]=value[i]
    return d1
print(dictionary(l1,l2))

{1: 'Nagpur', 2: 'pune', 3: 'mumbai', 4: 'delhi', 5: 'chennai'}


In [115]:
l1=[1,2,3,4,5]
l2=['Nagpur','pune','mumbai','delhi','chennai']
d1={}

for i,j in zip(l1,l2):
    d[i]=j
d

{1: 'Nagpur', 2: 'pune', 3: 'mumbai', 4: 'delhi', 5: 'chennai'}

In [116]:
l1=[1,2,3,4,5]
l2=['Nagpur','pune','mumbai','delhi','chennai']
d1={}

for i in range(len(l1)):
    d1[l1[i]]=l2[i]
d1

{1: 'Nagpur', 2: 'pune', 3: 'mumbai', 4: 'delhi', 5: 'chennai'}

In [117]:
l1=[1,2,3,4,5]
l2=['Nagpur','pune','mumbai','delhi','chennai']

d1={l1[i]:l2[i] for i in range(len(l1))}
d1


{1: 'Nagpur', 2: 'pune', 3: 'mumbai', 4: 'delhi', 5: 'chennai'}

In [118]:
l1=[1,2,3,4,5]
l2=['Nagpur','pune','mumbai','delhi','chennai']
d1={}
for i in range(len(l1)):
    d1[l1[i]]=l2[i]
d1

{1: 'Nagpur', 2: 'pune', 3: 'mumbai', 4: 'delhi', 5: 'chennai'}

In [119]:
print(dict(zip(l1,l2)))

{1: 'Nagpur', 2: 'pune', 3: 'mumbai', 4: 'delhi', 5: 'chennai'}


In [120]:
l1=[1,2,3,4,5]
l2=['Nagpur','pune','mumbai','delhi','chennai']
d3={}
 
for i,j in zip(l1,l2):
    d3[i]=j
d3

{1: 'Nagpur', 2: 'pune', 3: 'mumbai', 4: 'delhi', 5: 'chennai'}

In [121]:
l1=[1,2,3,4,5]
l2=['Nagpur','pune','mumbai','delhi','chennai']

dic={l1[i]:l2[i] for i in range(len(l1))}
dic

{1: 'Nagpur', 2: 'pune', 3: 'mumbai', 4: 'delhi', 5: 'chennai'}

In [122]:

d4={}
for i in range(1,11):
    d4[i]=i**3
d4


{1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216, 7: 343, 8: 512, 9: 729, 10: 1000}

In [123]:
d5={i:i**3 for i in range(1,11)}
d5

{1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216, 7: 343, 8: 512, 9: 729, 10: 1000}

In [129]:
n=int(input("Enter the number"))
for i in range(n):
    for j in range(n):
        print("*", end=" ")
    print()

Enter the number5
* * * * * 
* * * * * 
* * * * * 
* * * * * 
* * * * * 


In [131]:
n=int(input("Enter the number"))

for i in range(n):
    for j in range(i+1):
        print("*",end=" ")
    print()

Enter the number5
* 
* * 
* * * 
* * * * 
* * * * * 


In [132]:
n=int(input("Enter the number"))
for i in range(n):
    for j in range(n-i):
        print("*",end=" ")
    print()

Enter the number5
* * * * * 
* * * * 
* * * 
* * 
* 


In [139]:
n=int(input("Enter the number"))

for i in range(n):
    for j in range(n-i):
        print(" ",end=" ")
    for j in range(i+1):
        print("*",end=" ")
    print()

Enter the number5
          * 
        * * 
      * * * 
    * * * * 
  * * * * * 


In [141]:
n=int(input("Enter the number"))

for i in range(n):
    for j in range(i+1):
        print(" ",end=" ")
    for j in range(n-i):
        print("*", end=" ")
    print()

Enter the number5
  * * * * * 
    * * * * 
      * * * 
        * * 
          * 


In [147]:
n=int(input("Enter the number"))

for i in range(n):
    for j in range(n-i):
        print(" ",end=" ")
    for j in range(i):
        print("*",end=" ")
    for j in range(i+1):
        print("*",end=" ")
    print()

Enter the number5
          * 
        * * * 
      * * * * * 
    * * * * * * * 
  * * * * * * * * * 


In [151]:
n=int(input("Enter the number"))

for i in range(n):
    for j in range(i+1):
        print(" ",end=" ")
    for j in range((n-1)-i):
        print("*",end=" ")
    for j in range(n-i):
        print("*",end=" ")
    print()

Enter the number5
  * * * * * * * * * 
    * * * * * * * 
      * * * * * 
        * * * 
          * 


In [153]:
n=int(input("Enter the number"))

for i in range(n-1):
    for j in range(n-i):
        print(" ",end=" ")
    for j in range(i):
        print("*",end=" ")
    for j in range(i+1):
        print("*",end=" ")
    print()
for i in range(n):
    for j in range(i+1):
        print(" ",end=" ")
    for j in range((n-1)-i):
        print("*",end=" ")
    for j in range(n-i):
        print("*",end=" ")
    print()

Enter the number5
          * 
        * * * 
      * * * * * 
    * * * * * * * 
  * * * * * * * * * 
    * * * * * * * 
      * * * * * 
        * * * 
          * 


In [164]:
year=int(input("Enter year"))

if year%4==0:
    print("It's Leap Year")
elif year%100==0 and year%400==0:
    print("It's Leap Year")
else:
    print("Not Leap")



    

Enter year2124
It's Leap Year


In [170]:
# Remove Duplicate element
l=[1,5,6,1,2,6,5,8]
l1=[]
for i in l:
    if i not in l1:
        l1.append(i)
l1

[1, 5, 6, 2, 8]

In [171]:
for i in range(1,10+1):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [172]:
for i in range(10,0,-1):
    print(i)

10
9
8
7
6
5
4
3
2
1


In [174]:
n=int(input("Enter ele for checking frequency"))
l1=[1,2,3,4,1,2,3,2,1,5,6,4,1,5]

s=l1.count(n)
s

Enter ele for checking frequency1


4

In [176]:
# find the ele occuring on which index no

n=int(input("Enter ele for checking frequency"))
l1=[1,2,3,4,1,2,3,2,1,5,6,4,1,5]

index=0

while index<len(l1):
    if l1[index]==n:
        print(index, end=" ")
    index+=1

Enter ele for checking frequency1
0 4 8 12 

In [194]:
#prime

n=int(input("Enter number"))

def check_prime(num):
    flag=True
    if num>1:
        for i in range(2,num-1):
            if num%i==0:
                 flag=False
            
        return flag
print(check_prime(n))   

Enter number17
True


In [1]:
n=int(input("Enter number"))

def next_prime(num):
    num+=1
    while True:
        num+=1
        for i in range(2,num):
            if num%i==0:
                break
        else:
            return num
print(next_prime(n))

Enter number5
7


In [3]:
n=int(input("Enter number"))

for i in range(n):
    for j in range(n):
        print(str(n),end=" ")
    print()

Enter number4
4 4 4 4 
4 4 4 4 
4 4 4 4 
4 4 4 4 


In [6]:
n=int(input("Enter number"))

for i in range(1,n+1):
    for j in range(1,n+1):
        print(i,end=" ")
    print()

Enter number5
1 1 1 1 1 
2 2 2 2 2 
3 3 3 3 3 
4 4 4 4 4 
5 5 5 5 5 


In [7]:
n=int(input("Enter number"))

for i in range(n):
    for j in range(n):
        print("A",end=" ")
    print()

Enter number5
A A A A A 
A A A A A 
A A A A A 
A A A A A 
A A A A A 


In [8]:
n=int(input("Enter number"))

for i in range(n):
    for j in range(n):
        print(chr(65+i),end=" ")
    print()

Enter number5
A A A A A 
B B B B B 
C C C C C 
D D D D D 
E E E E E 


In [10]:
n=int(input("Enter number"))

for i in range(n):
    for j in range(n):
        print(j+1,end=" ")
    print()

Enter number5
1 2 3 4 5 
1 2 3 4 5 
1 2 3 4 5 
1 2 3 4 5 
1 2 3 4 5 


In [11]:
n=int(input("Enter number"))

for i in range(n):
    for j in range(n):
        print(chr(65+j),end=" ")
    print()

Enter number5
A B C D E 
A B C D E 
A B C D E 
A B C D E 
A B C D E 


In [14]:
n=int(input("Enter number"))

for i in range(n):
    for j in range(n):
        print(n-i,end=" ")
    print()

Enter number5
5 5 5 5 5 
4 4 4 4 4 
3 3 3 3 3 
2 2 2 2 2 
1 1 1 1 1 


In [15]:
n=int(input("Enter number"))

for i in range(n):
    for j in range(n):
        print(chr(69-i),end=" ")
    print()

Enter number5
E E E E E 
D D D D D 
C C C C C 
B B B B B 
A A A A A 


In [16]:
n=int(input("Enter number"))

for i in range(n):
    for j in range(n):
        print(n-j,end=" ")
    print()

Enter number5
5 4 3 2 1 
5 4 3 2 1 
5 4 3 2 1 
5 4 3 2 1 
5 4 3 2 1 


In [17]:
n=int(input("Enter number"))

for i in range(n):
    for j in range(n):
        print(chr(69-j),end=" ")
    print()

Enter number5
E D C B A 
E D C B A 
E D C B A 
E D C B A 
E D C B A 


In [18]:
n=int(input("Enter number"))

for i in range(n):
    for j in range(i+1):
        print("*",end=" ")
    print()

Enter number5
* 
* * 
* * * 
* * * * 
* * * * * 


In [20]:
n=int(input("Enter number"))

for i in range(n):
    for j in range(i+1):
        print(i+1,end=" ")
    print()

Enter number5
1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


In [21]:
n=int(input("Enter number"))

for i in range(n):
    for j in range(i+1):
        print(chr(65+i),end=" ")
    print()

Enter number5
A 
B B 
C C C 
D D D D 
E E E E E 


In [22]:
n=int(input("Enter number"))

for i in range(n):
    for j in range(i+1):
        print(n-j,end=" ")
    print()

Enter number5
5 
5 4 
5 4 3 
5 4 3 2 
5 4 3 2 1 


In [24]:
n=int(input("Enter number"))

for i in range(n):
    for j in range(i+1):
        print(chr(69-j),end=" ")
    print()

Enter number5
E 
E D 
E D C 
E D C B 
E D C B A 


In [31]:
n=int(input("Enter number"))

for i in range(n):
    for j in range(n-i):
        print("*",end=" ")
    print()

Enter number5
* * * * * 
* * * * 
* * * 
* * 
* 


In [34]:
n=int(input("Enter number"))

for i in range(n):
    for j in range(n-i):
        print(chr(65+i),end=" ")
    print()

Enter number5
A A A A A 
B B B B 
C C C 
D D 
E 


In [39]:
n=int(input("Enter number"))

for i in range(n):
    for j in range(n-i):
        print(" ",end=" ")
    for j in range(i):
        print('*',end=" ")
    for j in range(i+1):
        print('*',end=" ")
    print()

Enter number5
          * 
        * * * 
      * * * * * 
    * * * * * * * 
  * * * * * * * * * 


In [47]:
s="hi ashu keep practicing"

print(s.startswith('as',3,5))

True


In [52]:
mobile=input("Enter the mob no initials")

if mobile.startswith('+91'):
    print("Its india's number")
elif mobile.startswith('+12'):
    print("It's America's no")
elif mobile.startswith('+86'):
    print("It's china's no")

Enter the mob no initials+918766880347
Its india's number


In [53]:
s="hi ashu keep practicing"

print(s.endswith('ng'))

True


In [55]:
#  if user by mistake enter leading spaces while entering name then lstrip() function will remove the leding spaces
name=input("Enter name")

print(name)
name=name.lstrip()
print(name)


Enter name    ashu
    ashu
ashu


In [56]:
s='ashu'

print(s[::-1])

uhsa


In [58]:
s='ashu'
s1=""
l=len(s)
for i in range(l-1,0,-1):
    s1+=i
print(s1)

TypeError: can only concatenate str (not "int") to str

In [59]:
s='ashu'
s_r=""
l=len(s)

while l>0:
    s_r=s_r+s[l-1]
    l-=1
print(s_r)

uhsa


In [60]:
s='kolaveri'
s_r=""
for i in s:
    s_r=i+s_r
print(s_r)

irevalok


In [65]:
s1=s.replace('kola','sila')
print(s1)

solaveri


In [66]:
# find()  it gives the index number on 1st occurence of chararcter in a given string
st="chaitanya"
print(st.find('a'))

2


In [1]:
# fORMATTING IN PYTHON


name=input("Enter name")
age=int(input("Enter age"))
#simple formatting
print("hi my name is",name,"& my age is",age)

# f-string formatting
print(f"hi my name is {name} & my age is {age}")

Enter nameashu
Enter age24
hi my name is ashu & my age is 24
hi my name is ashu & my age is 24


In [2]:
city=input("Enter city name:")
state=input("Enter state name")

print( f"my city name is {city} and state name is {state}")

Enter city name:nagpur 
Enter state namemaharashtra
my city name is nagpur  and state name is maharashtra


In [6]:
s='ashu-is a boy'
print(s.split())

['ashu-is', 'a', 'boy']


In [16]:
l=['hi','hello','surya','rise']
s="".join(l)
print(s)
print(type(s))

hihellosuryarise
<class 'str'>


In [22]:
st="heLlo MuraRi"
st1=st.upper()
st1

'HELLO MURARI'

In [24]:
st2=st1.swapcase()
print(st2)

hello murari


In [25]:
st3=st2.title()
st3

'Hello Murari'

In [27]:
st4=st3.capitalize()
st4

'Hello murari'

In [1]:
import pandas as pd

In [2]:
l1=[5,4,9,7]
df=pd.DataFrame(l1)
df

0
0  5
1  4
2  9
3  7

In [3]:
df2=pd.DataFrame([[2,5,6],[9,9,5],[7,6,1]])
df2

0  1  2
0  2  5  6
1  9  9  5
2  7  6  1

In [14]:
d=[{'id':101,'name':'a'},{'id':102,'name':'b'}]
d

[{'id': 101, 'name': 'a'}, {'id': 102, 'name': 'b'}]

In [6]:
for key,value in d.items():
    print(key,value)

id 101
name a


In [7]:
for i in d:
    print(i,d[i])

id 101
name a


In [15]:
df1=pd.DataFrame(d)
df1

id name
0  101    a
1  102    b

In [24]:
df2=pd.DataFrame({'roll':[25,36,48],'name':['a','b','c']})
df2

roll name
0    25    a
1    36    b
2    48    c

In [18]:
df3=pd.DataFrame([{'pid':455,'pname':'Toy'},{'pid':658,'pname':'Bat'}])
df3

pid pname
0  455   Toy
1  658   Bat

In [100]:
l3=[[5,4,6],[7,4,2,3],[9,7,6,0]]
df4=pd.DataFrame(l3,columns=['a','b','c','d'])
df4.index=[101,102,103]
df4

a  b  c    d
101  5  4  6  NaN
102  7  4  2  3.0
103  9  7  6  0.0

In [101]:
df4.fillna({'d':'no'})
df4

a  b  c    d
101  5  4  6  NaN
102  7  4  2  3.0
103  9  7  6  0.0

In [99]:
import numpy as np

In [27]:
arr1=np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
arr2=np.arange(5,14).reshape(3,3)
arr2

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [30]:
arr3=arr1+arr2
arr3

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [33]:
arr4=arr1*arr2
arr4

array([[  0,   6,  14],
       [ 24,  36,  50],
       [ 66,  84, 104]])

In [34]:
ar=np.arange(15)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
ar=np.arange(15).reshape(3,5)
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [40]:
a_1=ar.reshape(-1)
a_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
a_1d=ar.flatten()
a_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
# Read csv file using pandas

df=pd.read_csv('D:\DUMMY_PROJECT_REPORT\info.csv')
df

id    name  age    city
0  101    ashu   25    pune
1  102     diu   20  nagpur
2  103  aniket   26  mumbai

In [44]:
type(df)

pandas.core.frame.DataFrame

In [45]:
type(id)

builtin_function_or_method

In [48]:
# seperated colm by #
df=pd.read_csv('D:\DUMMY_PROJECT_REPORT\info1.csv',sep='#')
df

id,name   age,city
0    101,ashu    25,pune
1     102,diu  20,nagpur
2  103,aniket  26,mumbai

In [52]:
df=pd.read_csv('D:\DUMMY_PROJECT_REPORT\info.csv',header=None)
df

0       1    2       3
0   id    name  age    city
1  101    ashu   25    pune
2  102     diu   20  nagpur
3  103  aniket   26  mumbai

In [68]:
labels=[10,20,30,40]

df1=pd.read_csv('D:\DUMMY_PROJECT_REPORT\info.csv',index_col=0)
#df1.columns=labels

df1

name  age    city
id                      
101    ashu   25    pune
102     diu   20  nagpur
103  aniket   26  mumbai

In [72]:
    # change the col names
col=['a','b','c','d']
df=pd.read_csv('D:\DUMMY_PROJECT_REPORT\info.csv',names=col)
df

#here one problem that previous header acts as 1st row

a       b    c       d
0   id    name  age    city
1  101    ashu   25    pune
2  102     diu   20  nagpur
3  103  aniket   26  mumbai

In [73]:
# soln 2:
col=['a','b','c','d']
df=pd.read_csv('D:\DUMMY_PROJECT_REPORT\info.csv')
df.columns=col
df

a       b   c       d
0  101    ashu  25    pune
1  102     diu  20  nagpur
2  103  aniket  26  mumbai

In [113]:
# Rename the specific column

df=pd.read_csv('D:\DUMMY_PROJECT_REPORT\info.csv')
df=df.rename(columns={'id':'Roll_no'})
df

Roll_no    name  age    city
0      101    ashu   25    pune
1      102     diu   20  nagpur
2      103  aniket   26  mumbai

In [116]:
df[['Roll_no','name']]

Roll_no    name
0      101    ashu
1      102     diu
2      103  aniket

In [117]:
df[['Roll_no','name']].T  #transpose(T) the DataFrame

0    1       2
Roll_no   101  102     103
name     ashu  diu  aniket

In [104]:
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [105]:
# convert ndarry into dataframe

df=pd.DataFrame(arr)
df.columns=['a','b','c']
df

a  b  c
0  0  1  2
1  3  4  5
2  6  7  8

In [106]:
# in loc end value is included
df.loc[0:2]


a  b  c
0  0  1  2
1  3  4  5
2  6  7  8

In [107]:
# in iloc the end value is excluded
df.iloc[0:2]


a  b  c
0  0  1  2
1  3  4  5

In [108]:
df.loc[[0,1]]

# here list use for only rows

a  b  c
0  0  1  2
1  3  4  5

In [109]:
df.loc[0,'b']
# row is 0 and col is 'b'

1

a  b  c
0  0  1  2
1  3  4  5
2  6  7  8

In [120]:
#Empty dataframe
dff=pd.DataFrame()
dff
type(dff)

pandas.core.frame.DataFrame

In [121]:
dn=pd.DataFrame(index=range(5),columns=['name','age'])
dn

name  age
0  NaN  NaN
1  NaN  NaN
2  NaN  NaN
3  NaN  NaN
4  NaN  NaN

In [122]:
dn['name']=['a','b','c','d','e']

In [123]:
dn

name  age
0    a  NaN
1    b  NaN
2    c  NaN
3    d  NaN
4    e  NaN

In [128]:
#Numpy
#array contain only single type of datatype

l1=[5,6,9,8,7]
arr=np.array(l1)
arr


array([5, 6, 9, 8, 7])

In [129]:
type(arr)

numpy.ndarray

In [130]:
#  if we use multiple datatypes in array then?

l1=[5,6,'A',8,7]
arr=np.array(l1)
arr


# It converted all array into string

array(['5', '6', 'A', '8', '7'], dtype='<U11')

In [131]:
type(arr)

numpy.ndarray

In [132]:
arr.ndim

1

In [133]:
arr.shape

(5,)

In [136]:
arr.dtype

dtype('<U11')

In [137]:
arr.size

5

In [140]:
np.arange(5,11)

#arange return array by default

array([ 5,  6,  7,  8,  9, 10])

In [142]:
arr=np.arange(5,11).reshape(2,3)
arr

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [144]:
arr=np.arange(5,21,2)
arr

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [151]:
age=[25,63,87,96,45,25]
w=[89,74,85,65,95,74]
df=pd.DataFrame(age)
df[1]=[86,74,62,58,79,87]
df.columns=['age','weight']
df

age  weight
0   25      86
1   63      74
2   87      62
3   96      58
4   45      79
5   25      87

In [154]:
df.groupby('weight').first()

age
weight     
58       96
62       87
74       63
79       45
86       25
87       25

In [4]:
unicode=u"\U0001f600\U0001F606\U0001F923"
unicode

'😀😆🤣'

In [1]:
num=11
i=1

while i<11:
    print(num*i)
    i=i+1


11
22
33
44
55
66
77
88
99
110


In [6]:
#Game Guess Number

import random

jackpot=random.randint(1,100)
guess=int(input("Enter your guess"))
count=1

while guess!= jackpot:
    if guess<jackpot:
        print("guess Higher")
    else:
        print("guess Lower")
    guess=int(input("Enter your guess"))
    count+=1

print("Adhbhut!!")
print("you took",count,"Attempts")

Enter your guess50
guess Higher
Enter your guess60
guess Higher
Enter your guess70
guess Higher
Enter your guess80
Adhbhut!!
you took 4 Attempts


In [12]:
for i in range(0,5):
    for j in range(i+1):
        print('*',end=" ")
    print()

* 
* * 
* * * 
* * * * 
* * * * * 


In [15]:
l=[1,2,3,4,5]
l[::-1]

[5, 4, 3, 2, 1]

In [16]:
def mul(a,b):
    return a*b
print(mul(8,3))

24


In [17]:
# Lambda Function

a=lambda x,y:x*y
print(a(8,3))

24


In [19]:
b=lambda x:"Even" if x%2==0 else "Odd"
print(b(8))

Even


In [21]:
##map Function

list(map(lambda X:X*2,[1,2,3,4,5,6]))


[2, 4, 6, 8, 10, 12]

In [2]:
##  Oops concept

class Car:
    def __init__(self):     #constructor
        print("Hello")
        
        
a=Car()     # a is object of car class

Hello


In [15]:
# In Many programmimng lang fraction Datatype is not there so,
# create fraction Datatype Using Oops concept

class Fraction:
    def __init__(self,n,d):
        self.numerator_val=n           # instance variable (public)
        self.denominator_val=d
        
        
    def __str__(self):
        return 'The Fraction Conversion is {}/{}'.format(self.numerator_val,self.denominator_val)
    
    def fun(self):                             ## Dummy function
        return "hello"
        

In [16]:
a=Fraction(2,3)

In [17]:
print(a)

The Fraction Conversion is 2/3


In [ ]:
# try with press tab button you will get instance var name in intellicence
a.

In [18]:
# Make instance variable private

# In Many programmimng lang fraction Datatype is not there so,
# create fraction Datatype Using Oops concept

class Fraction:
    def __init__(self,n,d):
        self.__numerator_val=n           # instance variable (private)
        self.__denominator_val=d
        
        
    def __str__(self):
        return 'The Fraction Conversion is {}/{}'.format(self.__numerator_val,self.__denominator_val)
    
    def fun(self):                             ## Dummy function
        return "hello"
        

In [19]:
s=Fraction(5,2)

In [20]:
print(s)

The Fraction Conversion is 5/2


In [ ]:
# try with press tab button you will get only method  name in intellicence

s.

In [13]:
## Iteration--> its general term for taking each iten of something one after another.
# if we apply loop on any list/tuple/set/dict  the fetching an item sequentially is called iteration

L=[1,2,3,4]
for i in L:
    print(i)
print(type(L))

1
2
3
4
<class 'list'>


In [16]:
## Iterable -->  Any Object on which we can perform loop is Called Iterable
# Iterable object have __iter__ magic function in its dir
#Iterable stores entire elements into memory at a time hence its slow to executes and not memory efficient
# Every the iterable are not  Iterator
# we can convert into iterator using (iter()) function


L=[1,2,3,4,5]

#check above object is iterable?
#1) apply loop:

for i in L:
    print(i)   #yes its iterable
#2) using dir() check for __iter__ magic function
print(dir(L))  # yes it has __iter__

## It take entire element to store memory
import sys
print(sys.getsizeof(L))   #It takes 120 bytes  


## Now Convert it into Iterator
print(type(iter(L)))




1
2
3
4
5
['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']
120
<class 'list_iterator'>
120


In [30]:
#generator  --> python generator are simple way of creating iterators

def gen_itor(num):
    yield num**2
    
gen=gen_itor(200)
for i in gen:
    print(i)

print(type(gen))
print(sys.getsizeof(gen))   ##for any digit  number size for memory will be same

40000
<class 'generator'>
112


In [32]:
## Generator Expression (Like list comprehension)
## use (---) instead of [---]
L=(x for x in range(10))
for i in L:
    print(i)
    

print(type(gen))
print(sys.getsizeof(gen))

0
1
2
3
4
5
6
7
8
9
<class 'generator'>
112


In [46]:
#User will input (3ages).Find the oldest one

a,b,c=input("Enter Ages").split()
a=int(a)
b=int(b)
c=int(c)

max=a
if max<b:
    max=b
if max<c:
    max=c
print(max)


Enter Ages99 21 52
99


In [48]:
#Write a program that will convert celsius value to fahrenheit

temp=float(input("Enter Temp value"))

fahrenheit=(temp*1.8)+32
print(fahrenheit)

Enter Temp value100
212.0


In [51]:
#User will input (2numbers).Write a program to swap the numbers

a,b=input('Enter two numbers').split()
a=int(a)
b=int(b)
print("Before swap",a,b)

a,b=b,a
print("After swap",a,b)

# without temp var
a=a+b
b=a-b
a=a-b
print("After swap",a,b)


Enter two numbers4 5
Before swap 4 5
After swap 5 4
After swap 4 5


In [52]:
#Write a program that will give you the sum of 3 digits

num=input("Enter Three Digit Num")
sum=0

for i in num:
    sum+=int(i)
print(sum)
    

Enter Three Digit Num123
6


In [61]:
#Write a program that will reverse a four digit number.Also it checks whether the reverse is true.

num=int(input("Enter Four Digit Num"))
l=len(str(num))
s=""
for i in range(l):
    rem=num%10
    new_num=num//10
    s=s+str(rem)
    num=new_num
print("Reverse_num is",s)

if s==num:
    print(True)
else:
    print(False)


Enter Four Digit Num1234
Reverse_num is 4321
False


In [62]:
l=[1,3,5,4]
del l[0]

In [63]:
l

[3, 5, 4]

In [64]:
a=l

In [65]:
a

[3, 5, 4]

In [67]:
a[0]

3

In [106]:
l=[1,2,3]
n=[]
new=[]
for i in l:
    a=l[-1]
del l[-1]
n.append(a)
n.extend(l)
new=n

In [107]:
l

[1, 2]

In [108]:
n

[3, 1, 2]

In [109]:
new

[3, 1, 2]

In [112]:
n.clear()

In [113]:
n

[]

In [116]:
l=[1,2,3]
s=[]

last=l[-1]
del l[-1]
s.append(last)
    

In [117]:
s

[3]

In [118]:
l

[1, 2]

In [138]:
a=[1,2,3]
k=2
queries=[0,1,2]


def circularArrayRotation(a, k, queries):
    # Write your code here
    l=[]
    new=[]
    for rotation in range(k):
        last_num=a[-1]
        del a[-1]
        l.append(last_num)
        l.extend(a)
        new=l
        a=[]
        a.extend(new)
        l.clear()
        new.clear()
        print(a)
    
        

circularArrayRotation(a,k,queries)        

[3, 1, 2]
[2, 3, 1]


In [5]:
nums=[2,14,18,22,22]
for i in nums:
    if nums.count(i)>1:
        print(True)
        
    else:
        print(False)

False
False
False
True
True


In [ ]:
num=int(input("Enter a Number")

In [3]:
l=['jay','ma']
s=''.join(l)

In [4]:
s

'jayma'

In [1]:
for i in range(5):
    for j in range(5-i):
        print("*",end=" ")
    print()

* * * * * 
* * * * 
* * * 
* * 
* 


In [7]:
no=int(input("Enter a number"))
i=1
while i<=10:
    print(f" {no}*{i} is",no*i)
    i+=1

Enter a number8
 8*1 is 8
 8*2 is 16
 8*3 is 24
 8*4 is 32
 8*5 is 40
 8*6 is 48
 8*7 is 56
 8*8 is 64
 8*9 is 72
 8*10 is 80


In [12]:
# Find random number
import random

a=random.randint(1,100)

In [13]:
a

91

In [ ]:
rand=random.randint(1,100)
no=int(input("Enter your guess number"))
def guess_game(num):
    count=0
    while num!=rand:
        if num > rand:
            count+=1
            print("Ohno!! guess lower")
        else:
            count+=1
            print("Ohno!! guess higher")
    
        no=int(input("Enter your guess number"))
      
    print(f"Correct Guess!! and attempt is{count}")
        
guess_game(no)


In [26]:

jackpot=random.randint(1,100)

guess=int(input("Guess the number"))
count=1

while guess!=jackpot:
    if guess<jackpot:
        print("Guess higher")
    else:
        print("Guess lower")
    
    guess=int(input("Guess the number"))
    count+=1    


print("Correct guess!!  and Attempt taken",count)

Guess the number50
Guess higher
Guess the number80
Guess higher
Guess the number90
Guess higher
Guess the number98
Guess lower
Guess the number95
Guess lower
Guess the number92
Correct guess!!  and Attempt taken 6


In [32]:
print(list(range(10,-1,-2)))

[10, 8, 6, 4, 2, 0]


In [41]:
num=int(input("Enter number"))

for i in range(num):
    for j in range(i+1):
        print("*",end=" ")
    print()

Enter number7
* 
* * 
* * * 
* * * * 
* * * * * 
* * * * * * 
* * * * * * * 


In [42]:
for i in range(1,11):
    if i==5:
        continue
    print(i)

1
2
3
4
6
7
8
9
10


In [45]:
ord('a')

97

In [46]:
import math
math.factorial(4)

24

In [48]:
import time
time.ctime()

'Tue Dec 19 16:05:53 2023'

In [49]:
s="hello how are you"

s.title()

'Hello How Are You'

In [60]:
l=s.split()
l

['hello', 'how', 'are', 'you']

In [61]:
n=[]
for i in l:
    n.append(i.capitalize())

In [66]:
" ".join(n)

'Hello How Are You'

In [67]:
sample="chaitanyalarokar@gmail.com"
sample[:sample.find('@')]


'chaitanyalarokar'

In [68]:
d={'name':'ashu','add':'pune','age':25}

In [69]:
d

{'name': 'ashu', 'add': 'pune', 'age': 25}

In [70]:
for i in d:
    print(i)

name
add
age


In [72]:
for i in d:
    print(d[i])

ashu
pune
25


In [74]:
for i in d:
    print(i,d[i])

name ashu
add pune
age 25


In [75]:
for key,value in d.items():
    print(key,value)

name ashu
add pune
age 25


In [76]:
d["father"]="Raju"

In [77]:
d

{'name': 'ashu', 'add': 'pune', 'age': 25, 'father': 'Raju'}

In [78]:
del d['age']

In [79]:
d

{'name': 'ashu', 'add': 'pune', 'father': 'Raju'}

In [82]:
# Arbitory Arguments

def flexi(*number):      #Its make list of numbers into tuples
    product=1
    for i in number:
        product*=i
    print(product)
    


In [83]:
print(flexi(1,2,3))

6
None


In [85]:
num=int(input("Enter number"))

def facto(no):
    fact=1
    for i in range(1,no+1):
        fact*=i
    print(fact)

facto(num)

Enter number4
24


In [1]:
num=int(input("Enter number"))

def facto(no):
    if no==1:
        return 1
    else:
        return no*facto(no-1)     # 5!=5*4!

facto(num)

Enter number4


24

In [14]:
s=input("Enter string")

s=s.lower()
i=0
j=len(s)-1

while i<j:
    if s[i]!=s[j]:
        print("Not Pallimdrome")
        break
    else:
        i+=1
        j-=1
        
        print("Its Pallimdrome")

        

Enter stringdfjgfjd
Its Pallimdrome
Not Pallimdrome


In [19]:
st=input("Enter string")

def palim(text):
    if len(text)<=1:
        print("It's Pallimdrome")
    else:
        if text[0]==text[-1]:
            palim(text[1:-1])
        else:
            print("Not Pallimdrome")
            
palim(st)


Enter stringbaab
It's Pallimdrome


In [25]:
def fiboo(m):
    if m==0 or m==1:
        return 1
    else:
        return fiboo(m-1)+fiboo(m-2)
    
print(fiboo(12))

233


In [33]:
#lambda function
# it has no name (Anonymeous function)
#it dont returns value but it returns function
# one line function
# not use for code reusability

s=lambda a:a**2
s(4)


16

In [34]:
b=lambda x,y:x*y
b(5,6)

30

In [40]:
l=[1,2,3,4,5,6,7,8,9,10]

f=list(map(lambda a:"Even" if a%2==0 else "odd",l))
f


['odd', 'Even', 'odd', 'Even', 'odd', 'Even', 'odd', 'Even', 'odd', 'Even']

In [42]:
l=[1,2,3,4,5,6,7,8,9,10]

f=list(filter(lambda a:a%2==0 ,l))
f


[2, 4, 6, 8, 10]

In [49]:
# 1 User will input (3ages).Find the oldest one

a=int(input("Enter first age"))
b=int(input("Enter second age"))
c=int(input("Enter third age"))

if a>b and a>c:
    print("a is oldest")
elif b>a and b>a:
    print("b is oldest")
else:
    print("c is olddest")



Enter first age9
Enter second age4
Enter third age52
c is olddest


In [50]:
#2. Write a program that will convert celsius value to fahrenheit

def cel_to_fah(val):
    return (val*9/5)+32

no=int(input("Enter celcius value"))
cel_to_fah(no)

Enter celcius value32


89.6

In [53]:
#3. User will input (2numbers).Write a program to swap the numbers

num1=int(input("Enter 1st num"))
num2=int(input("Enter 2nd num"))

def swap(a,b):
    print("Before swap a=",a,"b=",b)
    a=a+b
    b=a-b
    a=a-b
    print(" After Swap a=",a,"b=",b)
    
swap(num1,num2)

Enter 1st num3
Enter 2nd num2
Before swap a= 3 b= 2
 After Swap a= 2 b= 3


In [54]:
#4. Write a program that will give you the sum of 3 digits
num=input("Enter number")

def sum(no):
    sum=0
    for i in no:
        sum=sum+int(i)
    return sum
print(sum(num))
        

Enter number321
6


In [58]:
no=str(123)
print(str(no).reverse())

AttributeError: 'str' object has no attribute 'reverse'

In [ ]:
#5.Write a program that will reverse a four digit number.Also it checks whether the reverse is true.

num=input("Enter a number")

def reverse(no):
    return no.reverse()

In [60]:
dir(str)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',


In [61]:
# oops concepts

class atm:
    def __init__(self):
        print("Hello")
        
    def menu(self):
        pass
    
    

In [62]:
sbi=atm()

Hello


In [73]:
#create class of checking even and odd

class even_odd:
    def __init__(self,num):
        self.num=num
        self.Even_or_Odd(num)
        
    def Even_or_Odd(self,num):
        if self.num%2==0:
            print("Even")
        else:
            print("odd")
even_odd(2)           

Even


In [75]:
a=even_odd(5)

odd


In [130]:
class Atm():
    def __init__(self):
        self.pin=0
        self.balance=0
        self.menu()
        
    def menu(self):
        user_input=input(""" Hello! How would you like to proceed?
                1.Enter 1 to create pin
                2.Enter 2 for deposit
                3.Enter 3 for withdraw
                4.Enter 4 for check Balance
                5.Enter 5 for Exit
        """)
        
        if user_input=='1':
            self.create_pin()
        elif user_input=='2':
            self.deposit()
        elif user_input=='3':
            self.withdraw()
        elif user_input=='4':
            self.check_balance()
        else:
            print("session end")
            
    def create_pin(self):
        self.pin=int(input("Enter your pin"))
        print("pin set sucessfully")
        
    def deposit(self):
        temp=int(input("Enter your pin"))
        
        if temp==self.pin:
            deposit=int(input("Enter deposit amount"))
            self.balance+=deposit
            print("Deposit Sucessfully")
        else:
            print("Invalid pin")
            
    def withdraw(self):
        temp=int(input("Enter your pin"))
        
        if temp==self.pin:
            withdraw=int(input("Enter withdraw amount"))
            if withdraw<=self.balance:
                self.balance-=withdraw
                print("Operation Sucessful")
            else:
                print("Insufficient fund")
                
        else:
            print("Invalid pin")
            
    def check_balance(self):
        temp=int(input("Enter your pin"))
        if temp==self.pin:
            print(self.balance)
            
        else:
            print("Invalid pin")
        

In [124]:
sbi=Atm()

 Hello! How would you like to proceed?
                1.Enter 1 to create pin
                2.Enter 2 for deposit
                3.Enter 3 for withdraw
                4.Enter 4 for check Balance
                5.Enter 5 for Exit
        1
Enter your pin5353
pin set sucessfully


In [125]:
sbi.check_balance()

Enter your pin5353
0


In [126]:
sbi.deposit()

Enter your pin5353
Enter deposit amount50000
Deposit Sucessfully


In [127]:
sbi.check_balance()

Enter your pin5353
50000


In [128]:
sbi.withdraw()

Enter your pin5353
Enter withdraw amount10000
Operation Sucessful


In [129]:
sbi.check_balance()

Enter your pin5353
40000


In [131]:
sbi.menu()

 Hello! How would you like to proceed?
                1.Enter 1 to create pin
                2.Enter 2 for deposit
                3.Enter 3 for withdraw
                4.Enter 4 for check Balance
                5.Enter 5 for Exit
        5
exit


In [132]:
# This is user defined fraction datatype code

class fraction():
    def __init__(self,n,d):
        self.num=n
        self.den=d
        
    def __str__(self):
        
        """
            __str__ is one of the magic function.this method invoked by after __init__
            execute.used to cocat numerator and denominator values
        """
        return "{}/{}".format(self.num,self.den)
    
    
    def __add__(self,other):
        
        """
            __add__ is also magic method of python used to adding two 
            fraction values
        """
        temp_num=self.num*other.den+self.den*other.num
        temp_den=self.den*other.den
        
        return "{}/{}".format(temp_num,temp_den)

In [137]:
a=fraction(2,3)
b=fraction(3,4)

In [135]:
print(a)

2/3


In [138]:
print(b)

3/4


In [140]:
print(a+b)

17/12
